name: Build
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  headers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install depot tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$PWD/depot_tools" >> $GITHUB_PATH

      - name: Checkout v8
        run: |
          fetch v8
          cd v8
          git checkout ${{ steps.version.outputs.content }}
          gclient sync

      - name: Prepare out directory
        run: |
          mkdir ./out/
          cp -R ./v8/include/ ./out/
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: headers
          path: ./out/include/
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install depot tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$PWD/depot_tools" >> $GITHUB_PATH

      - name: Checkout v8
        run: |
          fetch v8
          cd v8
          git checkout ${{ steps.version.outputs.content }}
          gclient sync

      - name: Compile
        run: |
          cd v8
          tools/dev/gm.py x64.release

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: out
          path: ./v8/out/
          
  release:
    runs-on: ubuntu-latest
    needs: [headers, build]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Download headers artifact
        uses: actions/download-artifact@v3
        with:
          name: headers
          
      - name: Download out artifact
        uses: actions/download-artifact@v3
        with:
          name: out
          
      - uses: dev-drprasad/delete-tag-and-release@085c6969f18bad0de1b9f3fe6692a3cd01f64fe5
        with:
          delete_release: true
          tag_name: nightly
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename out
        run: |
          mv out.zip v8.zip

      - name: Create the release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: Nightly Build ${{ steps.vars.outputs.sha_short }}
          draft: false
          prerelease: false
          files: |
            headers.zip
            v8.zip
